aws:
  access_key: "enter your amazon key"
  secret_key: "enter your secret key"
  region: "eu-central-1"
  az: "eu-central-1a"

gcp:
  project_id: gcp-project
  region: europe-west1
  zone: europe-west1-b
  service_account: bosh

bosh:
  password: "changeme"
  keypair_name: "boshkey"
  public_key_path: "~/.ssh/bosh.key.pub"
  private_key_path: "~/.ssh/bosh.key"
  db_password: "changeme"

concourse:
  hostname: "ci.domain.io"
  dns_zone: "your_dns_zone_id"
  url: "http://ci.example.com"
  auth_username: "concourse"
  auth_password: "concourse"
  db_password: "changeme"
